[build]
  command = "npm run build"
  publish = "dist"
  
# This is the crucial section to fix the MIME type error.
# It tells the server to use 'text/javascript' for all files.
[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript" 
    
# Optional: Add Cache Control for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
